config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    root to: "dashboard#index"

    resources :themes
    resources :experiences
    resources :skills
    resources :themes
    resources :cvs
    resources :users
    resources :articles
    resources :dashboard, only: [:index]

    namespace :ahoy do
      resources :visits
      resources :events
    end
  end

  resources :experiences, except: [:index, :show] do
    patch :change_position, on: :member
  end

  resources :skills, except: [:index, :show]
  devise_for :users
  resources :users, only: [:edit, :update]
  resources :cvs, except: [:new] do
    get :export, on: :member
    get :test_export, on: :member
  end

  # Static pages
  root to: "pages#root"
  get "/terms", to: "pages#terms"
  get "/legal_notices", to: "pages#legal_notices"
  get "/services", to: "pages#services"
  get "/privacy_policy", to: "pages#privacy_policy"
  get "/contact", to: "pages#contact"
  get "/exemples_de_cv", to: "pages#examples"
  resources :articles, only: [:index, :show], path: 'blog'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  before_create :set_default_values
  after_create :add_default_content

  has_many :experiences, dependent: :destroy
  has_many :cvs, dependent: :destroy
  has_many :skills, dependent: :destroy
  has_many :links, dependent: :destroy
  has_many :visits, class_name: "Ahoy::Visit"

  validates :first_name, :last_name, presence: true

  def admin?
    email == "carl.quivron@gmail.com"
  end

  def work_experiences
    experiences.work
  end

  def education_experiences
    experiences.education
  end

  def language_skills
    skills.language
  end

  def tool_skills
    skills.tool
  end

  def skill_skills
    skills.skill
  end

  def full_name
    text = "#{first_name} #{last_name}"
    text.presence || email
  end

  private

  def set_default_values
    self.cv_email = email
    self.phone = "06 ..."
    self.address = "France"
    self.headline = "Poste actuel"
  end

  def add_default_content
    Experience.new_template(self, "work").save!
    Experience.new_template(self, "education").save!
    Skill.new_template(self, "skill").save!
    Skill.new_template(self, "tool").save!
    Skill.new_template(self, "language").save!
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users/devise_controller.rb
# frozen_string_literal: true

class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    include Rails.application.routes.url_helpers

    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      elsif controller.class.to_s == "Devise::RegistrationsController" && request.method == "DELETE"
        # Fix delete account
        redirect_to root_path
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.turbo_stream
        format.html { redirect_to user_url(@user) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :birthdate, :phone, :address, :headline, :about, :website, :interests, :cv_email, :avatar)
  end
end

app/views/users/_form.html.slim
= simple_form_for user, html: { id: "#{dom_id(user)}_form" } do |f|
  = hidden_field_tag :cv_id, @cv&.id
  = f.input :avatar
  = f.input :headline, placeholder: "Product Owner"
  = f.input :first_name, placeholder: "John"
  = f.input :last_name, placeholder: "Smith"
  = f.input :cv_email, as: :string, placeholder: "Email"
  = f.input :phone, as: :string, placeholder: "+33 6 00 00 00 00"
  = f.input :address, placeholder: "Paris"
  = f.input :about, placeholder: "Présentez vous en 1 phrase"
  = f.input :website, placeholder: "https://www.site.com"
  = f.button :submit

app/views/users/_user.html.slim
div.text-sm id="#{dom_id(user)}_item"
  p
    = @user.full_name
    br
    = @user.email
    br
    = @user.phone
    br
    = @user.address
    br
    = @user.headline
    br
    = @user.about
    br
    = @user.website

app/views/users/edit.html.slim
= turbo_frame_tag "edit_user" do
  = render "form", user: @user

app/views/users/show.html.slim
.cv-editor-layout.flex
  .w-1/2.bg-green-100
    h2.inline-block User
    = turbo_frame_tag "edit_user" do
      =< link_to "edit", edit_user_path(@user), class: 'btn'

    #user
      = render 'users/user', user: @user


    h2 Config
    div data-controller="color-picker"
      label.label.block Background color
      input.color-picker.field type="text" data-color-picker-target="source" value="#1F5710" data-action="keyup->color-picker#changeBackground"

    h2.inline-block Experiences
    = turbo_frame_tag "new_experience" do
      =< link_to "ajouter", new_experience_path, class: 'btn'

    #experiences
      - @user.experiences.each do |experience|
        = render 'experiences/experience', experience: experience
  .w-1/2.bg-slate-100
    #cv_container
      .wrapper
        = render "/themes/hello_world", user: @user

app/views/users/update.turbo_stream.slim
- if @user.errors.empty?

  = turbo_stream.replace "#{dom_id(@user)}_item" do
    = render "user", user: @user

  = turbo_stream.replace "user_cv_item" do
    = render "/themes/#{@theme_name}/user", user: @user

  = turbo_stream.replace "#{dom_id(@user)}_cv_item" do
    = render "/themes/#{@theme_name}/contact", user: @user

  - if Theme.name_with_avatar.include?(@theme_name)
    = turbo_stream.replace "avatar_cv_item" do
      = render "/themes/#{@theme_name}/avatar", user: @user

- else
  = turbo_stream.replace "user_form" do
    = render "form", user: @user