config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    root to: "dashboard#index"

    resources :themes
    resources :experiences
    resources :skills
    resources :themes
    resources :cvs
    resources :users
    resources :articles
    resources :dashboard, only: [:index]

    namespace :ahoy do
      resources :visits
      resources :events
    end
  end

  resources :experiences, except: [:index, :show] do
    patch :change_position, on: :member
  end

  resources :skills, except: [:index, :show]
  devise_for :users
  resources :users, only: [:edit, :update]
  resources :cvs, except: [:new] do
    get :export, on: :member
    get :test_export, on: :member
  end

  # Static pages
  root to: "pages#root"
  get "/terms", to: "pages#terms"
  get "/legal_notices", to: "pages#legal_notices"
  get "/services", to: "pages#services"
  get "/privacy_policy", to: "pages#privacy_policy"
  get "/contact", to: "pages#contact"
  get "/exemples_de_cv", to: "pages#examples"
  resources :articles, only: [:index, :show], path: 'blog'
end

app/models/skill.rb
# frozen_string_literal: true

class Skill < ApplicationRecord
  attr_accessor :newly_created

  enum item_type: { language: 0, tool: 1, skill: 2 }

  belongs_to :user

  def self.new_template(user, item_type)
    case item_type
    when "skill"
      Skill.new(
        user:,
        item_type:,
        name: "Compétence"
      )
    when "tool"
      Skill.new(
        user:,
        item_type:,
        name: "Outil"
      )
    when "language"
      Skill.new(
        user:,
        item_type:,
        name: "Francais",
        certification: "natif"
      )
    end
  end

  def newly_created!
    self.newly_created = true
  end
end

app/controllers/admin/skills_controller.rb
# frozen_string_literal: true

module Admin
  class SkillsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/skills_controller.rb
# frozen_string_literal: true

class SkillsController < ApplicationController
  before_action :set_skill, only: %i[edit update destroy]

  def new
    @skill = Skill.new(user: current_user, **skill_params)
  end

  def edit; end

  def create
    @skill = if params[:use_template] == "true"
               Skill.new_template(current_user, params[:item_type].to_s)
             else
               Skill.new(skill_params)
             end

    respond_to do |format|
      if @skill.save
        @skill.newly_created!
        format.html { redirect_to @skill }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
      format.turbo_stream
    end
  end

  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.turbo_stream
        format.html { redirect_to skill_url(@skill) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url }
      format.turbo_stream
    end
  end

  private

  def set_skill
    @skill = Skill.find(params[:id])
  end

  def skill_params
    params.require(:skill).permit(:user_id, :name, :level, :certification, :item_type)
  end
end

app/views/skills/_form.html.slim
= simple_form_for skill, html: { id: "#{dom_id(skill)}_form" } do |f|
  - if skill.errors.any?
    div style="color: red"
      h2 = "#{pluralize(skill.errors.count, 'error')} prohibited this skill from being saved:"
      ul
        - skill.errors.each do |error|
          li = error.full_message

  div
    = hidden_field_tag :cv_id, @cv&.id
    = f.hidden_field :user_id
    = f.hidden_field :item_type
    = f.input :name
    - if skill.language?
      = f.input :certification
    = f.button :submit, "Update"

app/views/skills/_new_btn.html.slim
= turbo_frame_tag "new_#{type}_skill" do
  =< link_to 'ajouter', new_skill_path(skill: {item_type: type}), class: 'text-primary-light  inline-block'

app/views/skills/_skill.html.slim
div id="#{dom_id(skill)}_item" *{data: { 'stream-enter-class': "slide-in", 'stream-exit-class': "slide-out" }}
  = turbo_frame_tag dom_id(skill) do
    div
      span =< "✗ #{skill.name}"

      =< link_to 'edit', edit_skill_path(skill), class: 'inline-block'
      =< link_to 'delete', skill_path(skill), data: { "turbo-method": :delete }, class: 'inline-block'

app/views/skills/create.turbo_stream.slim
- if @skill.errors.empty?
  - # Append content on form
  = turbo_stream.append "#{@skill.item_type}_skills" do
    = render "skill", skill: @skill

  - # Replace new form with Ajouter btn
  = turbo_stream.replace "new_#{@skill.item_type}_skill" do
    = render "/skills/new_btn", type: @skill.item_type

  - # Append content on CV
  = turbo_stream.append "cv_#{@skill.item_type}_skills" do
    = render "themes/#{@theme_name}/skill", skill: @skill

- else
  = turbo_stream.replace "#{dom_id(@skill)}_form" do
    = render "form", skill: @skill

app/views/skills/destroy.turbo_stream.slim
= turbo_stream.remove "#{dom_id(@skill)}_item"
= turbo_stream.remove "#{dom_id(@skill)}_cv_item"
= turbo_stream.remove "#{dom_id(@skill)}_tippy"

app/views/skills/edit.html.slim
= turbo_frame_tag dom_id(@skill) do
  = render "form", skill: @skill

app/views/skills/new.html.slim
= p "-------------------- new_#{@skill.item_type}_skill --------------------"
= turbo_frame_tag "new_#{@skill.item_type}_skill" do
  = render "form", skill: @skill

app/views/skills/update.turbo_stream.slim
- if @skill.errors.empty?
  = turbo_stream.replace "#{dom_id(@skill)}_item" do
    = render "skill", skill: @skill

  = turbo_stream.replace "#{dom_id(@skill)}_cv_item" do
    = render "/themes/#{@theme_name}/skill", skill: @skill

- else
  = turbo_stream.replace "#{dom_id(@skill)}_form" do
    = render "form", skill: @skill