config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    root to: "dashboard#index"

    resources :themes
    resources :experiences
    resources :skills
    resources :themes
    resources :cvs
    resources :users
    resources :articles
    resources :dashboard, only: [:index]

    namespace :ahoy do
      resources :visits
      resources :events
    end
  end

  resources :experiences, except: [:index, :show] do
    patch :change_position, on: :member
  end

  resources :skills, except: [:index, :show]
  devise_for :users
  resources :users, only: [:edit, :update]
  resources :cvs, except: [:new] do
    get :export, on: :member
    get :test_export, on: :member
  end

  # Static pages
  root to: "pages#root"
  get "/terms", to: "pages#terms"
  get "/legal_notices", to: "pages#legal_notices"
  get "/services", to: "pages#services"
  get "/privacy_policy", to: "pages#privacy_policy"
  get "/contact", to: "pages#contact"
  get "/exemples_de_cv", to: "pages#examples"
  resources :articles, only: [:index, :show], path: 'blog'
end

app/views/shared/_flashes.html.slim
- if flash.any?
  - flash.delete(:timedout)

  .fixed.inset-0.flex.items-end.px-4.py-6.pointer-events-none.sm:p-6.sm:items-start.z-10 aria-live="assertive"
    .w-full.flex.flex-col.items-center.space-y-4.sm:items-end
      - flash.each_with_index do |msg, index|
        - msg_type = msg[0]
        - message = msg[1]
        .flash_container.max-w-sm.w-full.bg-white.shadow-lg.rounded-lg.pointer-events-auto.ring-1.ring-black.ring-opacity-5.overflow-hidden id="flash_#{index}"
          .p-4
            - unless message.blank? || message.to_s.length.zero?
              .flex.items-center
                .flex-shrink-0
                  - if ['alert', 'error'].include? msg_type
                    i.text-error.gg-close-o
                  -else
                    i.text-success.gg-check-o
                .ml-3.w-0.flex-1 class="pt-0.5"
                  p.text-sm.font-medium.text-gray-900= message
                .ml-4.flex-shrink-0.flex
                  button.close-flash.bg-white.rounded-md.inline-flex.text-gray-400.hover:text-gray-500.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-indigo-500 data-index=index
                    span.sr-only Close
                    /! Heroicon name: solid/x
                    svg.h-5.w-5 aria-hidden="true" fill="currentColor" viewbox=("0 0 20 20") xmlns="http://www.w3.org/2000/svg"
                      path clip-rule="evenodd" d=("M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z") fill-rule="evenodd" /

  javascript:

    setTimeout(function(){ document.querySelectorAll('.flash_container').forEach((elem) => elem.remove()) }, 5000);
    document.querySelectorAll('.close-flash').forEach(item => {
      item.addEventListener('click', event => {
        document.querySelector(`#flash_${item.dataset.index}`).remove()
      })
    })

app/views/shared/_footer.html.slim
footer.bg-primary
  .max-w-7xl.mx-auto.py-12.px-4.overflow-hidden.sm:px-6.lg:px-8
    .pb-8.flex.items-baseline.justify-center.text-yellow
      = link_to 'Curyy', root_path, class: 'font-bold text-2xl'
      span.text-xs.ml-2 = t("app.meta.title")
    nav.-mx-5.-my-2.flex.flex-wrap.justify-center.text-white.flex-col.text-center.lg:flex-row.lg:text-left aria-label="Footer"
      .px-5.lg:border-r
        = link_to "Notre outil", services_path
      .px-5.lg:border-r
        = link_to "CGU", terms_path
      .px-5.lg:border-r
        = link_to "Mentions légales", legal_notices_path
      .px-5
        = link_to "Politique de confidentialité", privacy_policy_path

    p.pt-8.text-center.text-xs.text-gray-200 &copy; #{Date.current.year} Tous droits réservés.

app/views/shared/_head.html.slim
meta name="viewport" content="width=device-width, initial-scale=1.0"
meta name="theme-color" content="#3e0075"
= display_meta_tags(default_meta_tags)

- # Generated via tailwind.config.js
= stylesheet_link_tag "tailwind", "data-turbo-track": "reload"

- # Generated via cssbundling-rails
= stylesheet_link_tag "application", "data-turbo-track": "reload"

- # Generated with asset pipeline
= stylesheet_link_tag "application.assets", "data-turbo-track": "reload"

= javascript_include_tag "application", "data-turbo-track": "reload", defer: true


link href="https://fonts.googleapis.com" rel="preconnect"
link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"
link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&display=swap" rel="stylesheet"



link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
link href='https://css.gg/css' rel='stylesheet'


= csrf_meta_tags
= csp_meta_tag

app/views/shared/_navigation.html.slim
nav#header.full.lg:w-11/12.py-4.mx-auto
  .w-full.mx-auto.flex.flex-wrap.items-center.justify-between.mt-0.py-2
    .pl-4.flex.items-baseline
      = link_to 'Curyy', root_path, class: 'text-primary hover font-bold text-2xl'
      span.text-primary.text-xs.ml-2 = t("app.baseline")
    .block.lg:hidden.pr-4
      - if user_signed_in?
        button#nav-toggle.flex.items-center.justify-center.h-8.w-8
          i class="gg-menu"
      - else
        = link_to 'Créer mon CV', new_user_registration_path, class: "btn btn-primary"

    #nav-content.w-full.flex-grow.lg:flex.lg:items-center.lg:w-auto.hidden.mt-2.lg:mt-0.bg-white.lg:bg-transparent.text-primary.p-4.lg:p-0
      ul.list-reset.lg:flex.justify-end.flex-1.items-center
        - if !user_signed_in?
          li.mr-3
            = link_to 'Se connecter', new_user_session_path, class:'hover:text-primary-light transition'
        li.mr-3
          = link_to 'Créer mon CV', user_signed_in? ? cvs_path : new_user_registration_path, class: "btn btn-primary"
        - if user_signed_in?
          li.ml-2.mr-2.dropdown-container
            a.inline-block.border.rounded-full.p-2.transition href="#"
              i.gg-user-list style='--ggs: 1'
            ul.dropdown
              .border.px-2.bg-white
                li.border-b
                  = link_to edit_user_registration_path, class: 'flex items-center text-primary hover:text-primary-light transition py-2 px-4' do
                    i.gg-options.mr-1
                    span.pl-2 Mon compte
                li.border-b
                  = link_to cvs_path, class: "flex items-center text-primary hover:text-primary-light transition py-2 px-4" do
                    i.gg-file-document
                    span.pl-2 Mes CVs
                li
                  = link_to destroy_user_session_path, class: 'flex items-center inline-block text-primary hover:text-primary-light transition py-2 px-4', data: { "turbo-method": :delete } do
                    i.gg-log-out.mr-2 style='margin-left: 0'
                    span.pl-2 Deconnexion


  #mobile-menu.bg-primary.text-white.hidden
    ul.text-center.py-2
      li.py-2
        = link_to 'Mon compte', edit_user_registration_path
      li.py-2
        = link_to 'Mes CVs', cvs_path
      li.py-2
        = link_to 'Deconnexion', destroy_user_session_path, data: { "turbo-method": :delete }