config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    root to: "dashboard#index"

    resources :themes
    resources :experiences
    resources :skills
    resources :themes
    resources :cvs
    resources :users
    resources :articles
    resources :dashboard, only: [:index]

    namespace :ahoy do
      resources :visits
      resources :events
    end
  end

  resources :experiences, except: [:index, :show] do
    patch :change_position, on: :member
  end

  resources :skills, except: [:index, :show]
  devise_for :users
  resources :users, only: [:edit, :update]
  resources :cvs, except: [:new] do
    get :export, on: :member
    get :test_export, on: :member
  end

  # Static pages
  root to: "pages#root"
  get "/terms", to: "pages#terms"
  get "/legal_notices", to: "pages#legal_notices"
  get "/services", to: "pages#services"
  get "/privacy_policy", to: "pages#privacy_policy"
  get "/contact", to: "pages#contact"
  get "/exemples_de_cv", to: "pages#examples"
  resources :articles, only: [:index, :show], path: 'blog'
end

app/models/experience.rb
# frozen_string_literal: true

class Experience < ApplicationRecord
  attr_accessor :newly_created

  enum item_type: { work: 0, education: 1 }

  acts_as_list scope: [:item_type]

  belongs_to :user

  default_scope { order(position: :asc) }

  def self.new_template(user, item_type)
    case item_type
    when "work"
      Experience.new(
        user:,
        item_type:,
        start_date: "jan 2020",
        end_date: "aujourd'hui",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
        company: "Entreprise",
        location: "Ville",
        title: "Nom du poste"
      )
    when "education"
      Experience.new(
        user:,
        item_type:,
        start_date: "2010",
        end_date: "2015",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
        company: "Nom de l'école",
        location: "Paris",
        title: "Diplome"
      )
    end
  end

  def newly_created!
    self.newly_created = true
  end
end

app/controllers/admin/experiences_controller.rb
# frozen_string_literal: true

module Admin
  class ExperiencesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/experiences_controller.rb
# frozen_string_literal: true

class ExperiencesController < ApplicationController
  before_action :set_experience, only: %i[edit update destroy change_position]

  def new
    @experience = Experience.new(user: current_user, **experience_params)
  end

  def edit; end

  def create
    @experience = if params[:use_template] == "true"
                    Experience.new_template(current_user, params[:item_type].to_s)
                  else
                    Experience.new(experience_params)
                  end

    respond_to do |format|
      if @experience.save
        @experience.newly_created!
        format.html { redirect_to @experience }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
      format.turbo_stream
    end
  end

  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.turbo_stream
        format.html { redirect_to experience_url(@experience) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url }
      format.turbo_stream
    end
  end

  def change_position
    case params[:direction]
    when "lower"
      @experience.move_lower
    when "higher"
      @experience.move_higher
    end

    @higher_experience = @experience.higher_item
    @lower_experience = @experience.lower_item
    @direction = params[:direction]
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
  end

  def experience_params
    params.require(:experience).permit(:user_id, :start_date, :end_date, :current, :title, :description, :company, :location, :item_type)
  end
end

app/views/experiences/_experience.html.slim
div id="#{dom_id(experience)}_item" *{data: { 'stream-enter-class': "slide-in", 'stream-exit-class': "slide-out" }}
  = turbo_frame_tag dom_id(experience) do
    div
      span =< "✗ #{experience.title}"
      span.font-light.text-xs =< "@ #{experience.company}"

      =< link_to 'edit', edit_experience_path(experience), class: 'inline-block'
      =< link_to 'delete', experience_path(experience), data: { "turbo-method": :delete }, class: 'inline-block'

app/views/experiences/_form.html.slim
= simple_form_for experience, html: { id: "#{dom_id(experience)}_form" } do |f|
  - if experience.errors.any?
    div style="color: red"
      h2 = "#{pluralize(experience.errors.count, 'error')} prohibited this experience from being saved:"
      ul
        - experience.errors.each do |error|
          li = error.full_message

  div
    = hidden_field_tag :cv_id, @cv&.id
    = f.hidden_field :user_id
    = f.hidden_field :item_type
    = f.input :title
    = f.input :company
    = f.input :location
    = f.input :description
    = f.input :start_date
    = f.input :end_date
    = f.button :submit, "Update"

app/views/experiences/_new_btn.html.slim
= turbo_frame_tag "new_#{type}_experience" do
  =< link_to 'ajouter', new_experience_path(experience: {item_type: type}), class: 'text-primary-light inline-block'

app/views/experiences/change_position.turbo_stream.slim
- # Append content on CV
= turbo_stream.remove "#{dom_id(@experience)}_cv_item"

- if @direction == "lower"
  = turbo_stream.replace "#{dom_id(@lower_experience)}_cv_item" do
    = render "themes/#{@theme_name}/experience", experience: @experience
- elsif @direction == "higher"

app/views/experiences/create.turbo_stream.slim
- if @experience.errors.empty?
  - # Append content on form
  = turbo_stream.append "#{@experience.item_type}_experiences" do
    = render "experience", experience: @experience

  - # Replace new form with Ajouter btn
  = turbo_stream.replace "new_#{@experience.item_type}_experience" do
    = render "/experiences/new_btn", type: @experience.item_type

  - # Append content on CV
  = turbo_stream.append "cv_#{@experience.item_type}_experiences" do
    = render "themes/#{@theme_name}/experience", experience: @experience

- else
  = turbo_stream.replace "#{dom_id(@experience)}_form" do
    = render "form", experience: @experience

app/views/experiences/destroy.turbo_stream.slim
= turbo_stream.remove "#{dom_id(@experience)}_item"
= turbo_stream.remove "#{dom_id(@experience)}_cv_item"
= turbo_stream.remove "#{dom_id(@experience)}_tippy"

app/views/experiences/edit.html.slim
= turbo_frame_tag dom_id(@experience) do
  = render "form", experience: @experience

app/views/experiences/new.html.slim
= turbo_frame_tag "new_#{@experience.item_type}_experience" do
  = render "form", experience: @experience

app/views/experiences/update.turbo_stream.slim
- if @experience.errors.empty?
  = turbo_stream.replace "#{dom_id(@experience)}_item" do
    = render "experience", experience: @experience

  = turbo_stream.replace "#{dom_id(@experience)}_cv_item" do
    = render "/themes/#{@theme_name}/experience", experience: @experience

- else
  = turbo_stream.replace "#{dom_id(@experience)}_form" do
    = render "form", experience: @experience